### ISSUE TITLE
PublicIPv4 of EC2Instance always takes 1st IP address from Hardware

### ISSUE THREAD

**Issue by rockc2020** [tinkerbell/hegel#325]
In my tinkerbell stack k8s cluster for CAPT, I had a `Hardware` resource which includes the follow fields:
```yaml
  metadata:
    instance:
      hostname: host-01
      id: 10:70:fd:19:e6:56
      ips:
        - address: 10.52.107.72
          family: 4
          gateway: 10.52.107.65
          netmask: 255.255.255.192
          public: false
        - address: 69.19.7.42
          family: 4
          gateway: 69.19.7.33
          netmask: 255.255.255.224
          public: true
```
When the hegel was called with `local-ipv4` and `public-ipv4`, it always returns the local one `10.52.107.72`.
- `curl -v http://10.52.107.71:50061/2009-04-04/meta-data/local-ipv4`
- `curl -v http://10.52.107.71:50061/2009-04-04/meta-data/public-ipv4`

## Expected Behaviour

- `curl -v http://10.52.107.71:50061/2009-04-04/meta-data/local-ipv4`, it should return `10.52.107.72`
- `curl -v http://10.52.107.71:50061/2009-04-04/meta-data/public-ipv4`, it should return `69.19.7.42`.

## Current Behaviour

- `curl -v http://10.52.107.71:50061/2009-04-04/meta-data/local-ipv4`, it returns `10.52.107.72`.
- `curl -v http://10.52.107.71:50061/2009-04-04/meta-data/public-ipv4`, it returns `10.52.107.72`.

## Possible Solution

In the `backend.go` file, it should take values from the `ip` iteratively in the loop.

**Current code**
https://github.com/tinkerbell/hegel/blob/main/internal/backend/kubernetes/backend.go#L185-L200
```go
                for _, ip := range hw.Spec.Metadata.Instance.Ips {
                        // Public IPv4
                        if ip.Family == 4 && ip.Public && i.Metadata.PublicIPv4 == "" {
                                i.Metadata.PublicIPv4 = hw.Spec.Metadata.Instance.Ips[0].Address
                        }


                        // Private IPv4
                        if ip.Family == 4 && !ip.Public && i.Metadata.LocalIPv4 == "" {
                                i.Metadata.LocalIPv4 = hw.Spec.Metadata.Instance.Ips[0].Address
                        }


                        // Public IPv6
                        if ip.Family == 6 && i.Metadata.PublicIPv6 == "" {
                                i.Metadata.PublicIPv6 = hw.Spec.Metadata.Instance.Ips[0].Address
                        }
                }
```
**Possible fix**
```go
                for _, ip := range hw.Spec.Metadata.Instance.Ips {
                        // Public IPv4
                        if ip.Family == 4 && ip.Public && i.Metadata.PublicIPv4 == "" {
                                i.Metadata.PublicIPv4 = ip.Address
                        }


                        // Private IPv4
                        if ip.Family == 4 && !ip.Public && i.Metadata.LocalIPv4 == "" {
                                i.Metadata.LocalIPv4 = ip.Address
                        }


                        // Public IPv6
                        if ip.Family == 6 && i.Metadata.PublicIPv6 == "" {
                                i.Metadata.PublicIPv6 = ip.Address
                        }
                }
```

## Steps to Reproduce (for bugs)

It's simple as described in the summary.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
Linux

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:
I run Tinkerbell on bare metal servers to work with CAPT.

* Link to your project or a code example to reproduce issue:
