### ISSUE TITLE
Calls from not TrustedProxies return 500

### ISSUE THREAD

**Issue by eidmantas** [tinkerbell/hegel#424]
Hello,

We've been running into an issue where we're getting 500, "no hardware found" using hegel helm chart.

Yesterday managed to get it working:
- by creating an additional hardware object.
- today changed HEGEL_TRUSTED_PROXIES to `0.0.0.0/0` to allow debug requests - started working again.
Seem completely unrelated.

Haven't had time to go through the mechanism from which using kubernetes backend info is collected. 
Was wondering if maybe somebody has seen similar behaviour recently? 

```
  containers:
    - args:
        - '--backend=kubernetes'
        - '--http-addr=:50061'
        - '--kubernetes-namespace=tinkerbell'
      env:
        - name: HEGEL_TRUSTED_PROXIES
          value: 10.5.0.0/16
```

```
{
    "level": "error",
    "client_ip": "10.5.0.23",
    "method": "GET",
    "status_code": 500,
    "path": "/metadata",
    "latency": "167.12µs",
    "error": "no hardware found",
    "time": "2025-04-03T06:26:23Z",
    "caller": "/home/runner/work/hegel/hegel/internal/logger/logger.go:53",
    "message": "all_errors"
}
```
